"""
OpenAI-compatible chat completion response models.

Follows OpenAI API specification:
https://platform.openai.com/docs/api-reference/chat/object
"""

from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ChatCompletionMessage(BaseModel):
    """Message generated by the model."""

    role: str = Field(description="Role of the message author (usually 'assistant')")
    content: str | None = Field(
        default=None,
        description="Content of the message",
    )
    function_call: dict[str, Any] | None = Field(
        default=None,
        description="Deprecated: function call made by the model",
    )
    tool_calls: list[dict[str, Any]] | None = Field(
        default=None,
        description="Tool calls made by the model",
    )


class ChatCompletionChoice(BaseModel):
    """A single completion choice."""

    index: int = Field(description="Index of this choice in the list")
    message: ChatCompletionMessage = Field(description="Generated message")
    finish_reason: str | None = Field(
        default=None,
        description="Reason for completion (stop, length, tool_calls, etc.)",
    )
    logprobs: dict[str, Any] | None = Field(
        default=None,
        description="Log probabilities (if requested)",
    )


class ChatCompletionUsage(BaseModel):
    """Token usage statistics."""

    prompt_tokens: int = Field(description="Tokens in the prompt")
    completion_tokens: int = Field(description="Tokens in the completion")
    total_tokens: int = Field(description="Total tokens used")


class ChatCompletionResponse(BaseModel):
    """
    OpenAI-compatible chat completion response.

    Returned for both sync and streaming (final message) completions.
    """

    id: str = Field(description="Unique completion ID")
    object: str = Field(
        default="chat.completion",
        description="Object type (always 'chat.completion')",
    )
    created: int = Field(description="Unix timestamp of creation")
    model: str = Field(description="Model used for completion")
    choices: list[ChatCompletionChoice] = Field(
        description="List of completion choices",
        min_length=1,
    )
    usage: ChatCompletionUsage | None = Field(
        default=None,
        description="Token usage statistics",
    )
    system_fingerprint: str | None = Field(
        default=None,
        description="System fingerprint for reproducibility",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "chatcmpl-abc123",
                "object": "chat.completion",
                "created": 1677652288,
                "model": "gpt-4o-mini",
                "choices": [
                    {
                        "index": 0,
                        "message": {
                            "role": "assistant",
                            "content": "Hello! How can I help you today?",
                        },
                        "finish_reason": "stop",
                    }
                ],
                "usage": {
                    "prompt_tokens": 20,
                    "completion_tokens": 10,
                    "total_tokens": 30,
                },
            }
        }
    )


class ChatCompletionStreamChunk(BaseModel):
    """
    Chunk from a streaming chat completion.

    Used for SSE streaming responses (stream=true).
    """

    id: str = Field(description="Unique completion ID")
    object: str = Field(
        default="chat.completion.chunk",
        description="Object type (always 'chat.completion.chunk')",
    )
    created: int = Field(description="Unix timestamp of creation")
    model: str = Field(description="Model used for completion")
    choices: list[dict[str, Any]] = Field(
        description="List of chunk choices with deltas",
        min_length=1,
    )
    system_fingerprint: str | None = Field(
        default=None,
        description="System fingerprint for reproducibility",
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "id": "chatcmpl-abc123",
                "object": "chat.completion.chunk",
                "created": 1677652288,
                "model": "gpt-4o-mini",
                "choices": [
                    {
                        "index": 0,
                        "delta": {"content": "Hello"},
                        "finish_reason": None,
                    }
                ],
            }
        }
    )
